// Shared types for the AI chat application, mirrored between the client and
// the server (`@shared/chat`). Keeping these in one place prevents drift
// between the HTTP API contract and the frontend models.

/**
 * The wire shape of a chat message — what `/api/chat` accepts and what
 * Workers AI expects in `messages`. Kept separate from the storage
 * `ChatMessage` so branch metadata (ids, parents, timestamps) never leaks
 * into request payloads.
 */
export interface WireChatMessage {
  role: "user" | "assistant" | "system";
  content: string;
  /**
   * Optional reasoning / chain-of-thought content (generated by reasoning
   * models before the final answer). Persisted with the message so it can be
   * shown/hidden in the UI without re-requesting.
   */
  reasoning?: string;
}

/**
 * A single stored chat message node. Messages form a tree (`parentId`), so a
 * conversation can hold persistent sibling branches (edit / try-again
 * variants) exactly like ChatGPT. The visible thread is the path from the
 * root to `Conversation.leafId`.
 */
export interface ChatMessage extends WireChatMessage {
  id: string;
  parentId: string | null;
  /** Creation time — also defines sibling order (oldest first). */
  createdAt: number;
  /**
   * Which child is on the currently-active branch when the path passes
   * through this node. Navigation memory for sibling switching.
   */
  activeChildId?: string;
  /**
   * Set when generating this (assistant) reply failed or was stopped before
   * producing content. The node is deliberately kept in the tree so turn
   * alternation survives; the UI renders an error bubble with a retry
   * action. Storage-only — never sent on the wire.
   */
  error?: string;
}

/** A full conversation history: a tree of messages plus the active branch. */
export interface Conversation {
  id: string;
  title: string;
  model: string;
  createdAt: number;
  updatedAt: number;
  /** Flat list of all message nodes across every branch. */
  messages: ChatMessage[];
  /** Leaf of the currently active branch (thread = path root → leaf). */
  leafId: string | null;
}

/** Generation knobs that can be adjusted per-request from the UI. */
export interface GenerationParams {
  temperature?: number;
  topP?: number;
  stream?: boolean;
}

/**
 * Reasoning effort is a first-class concept used by reasoning models, matching
 * the Workers AI definition. `off` disables reasoning entirely
 * (`enable_thinking`); `minimal` is the lightest possible reasoning pass.
 */
export type ReasoningEffort = "off" | "minimal" | "low" | "medium" | "high";

/**
 * Defaults for new conversations, persisted to localStorage. A subset of
 * `Conversation`-independent global settings the user tweaks once.
 */
export interface DefaultChatOptions {
  model: string;
  reasoningEffort: ReasoningEffort;
  params: GenerationParams;
  /** Default text-to-image model id for the Workers AI Draw page. */
  drawModel?: string;
}

/** Schema (tag) objects emitted over the SSE stream. */
export interface StreamEvent {
  type: "delta" | "done" | "error";
  /** For `delta` — the increment of assistant text. */
  delta?: string;
  /** For `done` — the fully accumulated message. */
  content?: string;
  /** For `error` — a human-readable reason. */
  message?: string;
}

/**
 * Namespace the client-side persistence under. Bumped to `v2` when messages
 * became a branch tree; the client migrates `v1` data on load.
 */
export const STORAGE_KEY = "conversations:v2";
